In [15]:
import pandas as pd

In [16]:
#итання csv файлів з використанням стандартногоо декодування (utf-8)
df = pd.read_csv(r'C:\Users\phils\Documents\Python Project\stack-overflow-developer-survey-2025\survey_results_public.csv', encoding='utf-8')
df1 = pd.read_csv(r'C:\Users\phils\Documents\Python Project\stack-overflow-developer-survey-2025\survey_results_schema.csv', encoding='utf-8')

C:\Users\phils\AppData\Local\Temp\ipykernel_19048\574753445.py:2: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'C:\Users\phils\Documents\Python Project\stack-overflow-developer-survey-2025\survey_results_public.csv', encoding='utf-8')

In [19]:
#налаштування параметрів для відображення всіх колонок в DataFrame
pd.set_option('display.max_columns', None)

In [27]:
# DataFrame, опитування респондентів
df.head(5)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [29]:
# DF1 з питаннями опитування
with pd.option_context('display.max_colwidth', None, 'display.max_rows', 150):
    display(df1)

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Reputation for quality,5.0
5,QID18,TechEndorse_6,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Connected to an open-source project,6.0
6,QID18,TechEndorse_7,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Good brand and public image,7.0
7,QID18,TechEndorse_8,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Reliability and low latency,8.0
8,QID18,TechEndorse_9,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Costs are manageable,9.0
9,QID18,TechEndorse_13,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Other (please specify):,10.0
10,QID18,TechEndorse_13_TEXT,What attracts you to a technology or causes you to endorse it (most to least important)?,RO,Other (please specify): - Text,13.0
11,QID19,TechOppose_1,What would turn you off or cause you to reject it (most to least important)?,RO,Lack of AI or AI agents,1.0
12,QID19,TechOppose_2,What would turn you off or cause you to reject it (most to least important)?,RO,Poor usability,2.0
13,QID19,TechOppose_3,What would turn you off or cause you to reject it (most to least important)?,RO,Lack of or sub-par API,3.0
14,QID19,TechOppose_5,What would turn you off or cause you to reject it (most to least important)?,RO,Inefficient or time-costly,4.0
15,QID19,TechOppose_7,What would turn you off or cause you to reject it (most to least important)?,RO,Prohibitive pricing,5.0
16,QID19,TechOppose_9,What would turn you off or cause you to reject it (most to least important)?,RO,Security or privacy concerns,6.0
17,QID19,TechOppose_11,What would turn you off or cause you to reject it (most to least important)?,RO,Availability of better alternatives,7.0
18,QID19,TechOppose_13,What would turn you off or cause you to reject it (most to least important)?,RO,Outdated or obsolete technology or features,8.0
19,QID19,TechOppose_16,What would turn you off or cause you to reject it (most to least important)?,RO,Ethical concerns,9.0
20,QID19,TechOppose_15,What would turn you off or cause you to reject it (most to least important)?,RO,Other (please specify):,10.0
21,QID19,TechOppose_15_TEXT,What would turn you off or cause you to reject it (most to least important)?,RO,Other (please specify): - Text,15.0
22,QID27,JobSatPoints_1,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Control over the level of quality in projects,1.0
23,QID27,JobSatPoints_2,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Autonomy and trust to manage your own tasks,2.0
24,QID27,JobSatPoints_16,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,You like your manager,3.0
25,QID27,JobSatPoints_3,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Collaboration and support from a team,4.0
26,QID27,JobSatPoints_4,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Expert mentors,5.0
27,QID27,JobSatPoints_5,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Opportunities to mentor and lead junior-level coworkers,6.0
28,QID27,JobSatPoints_6,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Developing specialized expertise,7.0
29,QID27,JobSatPoints_7,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Solving real-world problems,8.0
30,QID27,JobSatPoints_8,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Job stability and career growth with a single employer,9.0
31,QID27,JobSatPoints_9,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Innovation through solving challenging and complex problems,10.0
32,QID27,JobSatPoints_10,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Working with new technologies and tools,11.0
33,QID27,JobSatPoints_11,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Competitive pay and benefits,12.0
34,QID27,JobSatPoints_13,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Recognition from peers for your work,13.0
35,QID27,JobSatPoints_14,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Recognition from leadership for your work,14.0
36,QID27,JobSatPoints_15,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Other (please specify):,15.0
37,QID27,JobSatPoints_15_TEXT,"Rank the following attributes of your current professional job in technology according to those that contribute your job satisfaction so that the first is the most important, last is least important (if you just started a new job, consider the job you spent the most time at in the past year):",RO,Other (please specify): - Text,15.0
38,QID76,SO_Actions_1,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Browse content related to Q&A posts I recently viewed,1.0
39,QID76,SO_Actions_16,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Read and/or vote on comments for a Question or Answer I am interested in,2.0
40,QID76,SO_Actions_3,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Bookmark posts to look at later,3.0
41,QID76,SO_Actions_4,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,"Directly open a Q&A post via search, documentation or a peer",4.0
42,QID76,SO_Actions_5,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Ask a question,5.0
43,QID76,SO_Actions_6,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Answer a question,6.0
44,QID76,SO_Actions_9,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Comment on Q&A posts,7.0
45,QID76,SO_Actions_7,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Upvote/Downvote Q&A posts,8.0
46,QID76,SO_Actions_10,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Use discussion or chat feature,9.0
47,QID76,SO_Actions_15,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Other (write in):,10.0
48,QID76,SO_Actions_15_TEXT,"When visiting Stack Overflow, which following activities are you most interested in? Please rank the following so the first activity is what most interests you and last is your least interested activity.",RO,Other (write in): - Text,15.0
49,QID3,MainBranch,Are you someone who writes code? Please select one of the following options that best describes you today.,MC,NaN,NaN
50,QID4,Age,What is your age?,MC,NaN,NaN
51,QID9,EdLevel,Which of the following best describes the highest level of formal education that you’ve completed?,MC,NaN,NaN
52,QID7,Employment,Which of the following best describes your current employment status?<br>,MC,NaN,NaN
53,QID8,EmploymentAddl,Which of the following <strong>additional</strong> activities are you currently engaged in?,MC,NaN,NaN
54,QID14,WorkExp,"How many years of professional work experience do you have? Please round to the nearest whole number, excluding any decimal points. If your answer is '0', please leave blank.",TE,NaN,NaN
55,QID10,LearnCodeChoose,Did you begin learning to code or learn a new coding skill/programming language in the last year?,MC,NaN,NaN
56,QID11,LearnCode,How did you learn to code in the past year? Select all that apply.,MC,NaN,NaN
57,QID12,LearnCodeAI,Did you spend time in the last year learning AI programming or AI-enabled tooling on your own or at work?,MC,NaN,NaN
58,QID32,AILearnHow,How did you learn to code for AI in the past year? Select all that apply.,MC,NaN,NaN
59,QID13,YearsCode,"Including any education, how many years have you been coding in total? Please round to the nearest whole number, excluding any decimal points.",TE,NaN,NaN
60,QID15,DevType,Which of the following describes your current job or the job you had for the most time in the past year?,MC,NaN,NaN
61,QID16,OrgSize,"Approximately how many people are employed by your employer? This should only include your primary company, and if there was more than one employer please consider the one you spent most of your time working for in the past year.",MC,NaN,NaN
62,QID23,ICorPM,Are you an individual contributor or people manager?,MC,NaN,NaN
63,QID24,RemoteWork,Which best describes your current work situation?,MC,NaN,NaN
64,QID17,PurchaseInfluence,Have you <strong>influenced or endorsed</strong> a new technology purchase at your organization or sole proprietor job in the past year?,MC,NaN,NaN
65,QID33,TechEndorseIntro,"When you&rsquo;re in a position to <strong>influence or endorse a technology</strong>, whether at work, for school, or for a personal project you&rsquo;re responsible for, what features or attributes matter most when deciding to support a tool? What factors would be deal-breakers?<br />\n<br />\nFirst, select the context (work, school, personal project). Then, rank the following features in order of importance.​​​​​​",MC,NaN,NaN
66,QID25,Industry,What industry do you work for in?,MC,NaN,NaN
67,QID26,JobSat,How satisfied are you in your current professional developer role?,MC,NaN,NaN
68,QID28,AIThreat,Do you believe AI is a threat to your current job?,MC,NaN,NaN
69,QID29,NewRole,Have you considered a career change or transitioned into a new role in the past year?,MC,NaN,NaN
70,QID30,ToolCountWork,"For your <b>primary work role</b> (student, developer, or technologist) over the past year:\n<br><br>Excluding general operating systems (like Windows or macOS) and web browsers, <b>how many distinct software applications or platforms</b> did you regularly use to create, analyze, manage, or share information in order to do your job?\n\nPlease enter a whole number below with no punctuation, or leave blank.",TE,NaN,NaN
71,QID31,ToolCountPersonal,"<b></b>For your <b>side projects or other personal work</b> over the past year (focus on the project you spent the most time on if applicable):\n<br><br>Excluding general operating systems and web browsers, how many <b>distinct software applications or platforms</b> did you regularly use to do your job? Please enter a whole number below with no punctuation, or leave blank.",TE,NaN,NaN
72,QID20,Country,Where do you live?,MC,NaN,NaN
73,QID21,Currency,"Which currency do you use day-to-day? If your answer is complicated, please pick the one you're most comfortable estimating in.",MC,NaN,NaN
74,QID22,CompTotal,"What is your current total <b>annual</b> compensation (salary, bonuses, and perks, before taxes and deductions) in terms of your day-to-day currency? Please enter a whole number in the box below, without any punctuation. If you are paid hourly, please estimate an equivalent yearly salary. If you prefer not to answer, please leave the box empty.",TE,NaN,NaN
75,QID44,LanguageChoice,"Did you work with programming, scripting and markup languages in the last year or do you plan to in the year to come? Here, we are referring to anything you use that is conventionally referred to as code.",MC,NaN,NaN
76,QID34,Language,"Which <b>programming, scripting, and markup languages</b> have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the language and want to continue to do so, please check both boxes in that row.)",Matrix,NaN,NaN
77,QID51,LanguagesHaveEntry,"Was the programming language you use not listed above? List below, separated by a comma and a space for each, the programming language(s) <strong>you used in the past year</strong>.",TE,NaN,NaN
78,QID52,LanguagesWantEntry,"Was the programming language you want to use not listed above? List below, separated by a comma and a space for each, the programming language(s) <strong>you want to use next year</strong>.",TE,NaN,NaN
79,QID45,DatabaseChoice,"Did you work with database environments in the last year or do you plan to in the year to come? Here, we are referring to a system of managing structured data, mostly outside of your local machine.",MC,NaN,NaN
80,QID35,Database,"Which <b>database environments </b>have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the database and want to continue to do so, please check both boxes in that row.)",Matrix,NaN,NaN
81,QID54,DatabaseHaveEntry,"Was the database environment you use not listed above? List below, separated by a comma and a space for each, what <strong>you used in the past year</strong>.",TE,NaN,NaN
82,QID55,DatabaseWantEntry,"Was the database environment you want to use not listed above? List below, separated by a comma and a space for each, what <strong>you want to use next year</strong>.",TE,NaN,NaN
83,QID46,PlatformChoice,"Did you work with cloud platforms, containerization/orchestration tools, package managers, build tools or infrastructure as code solutions in the last year or do you plan to in the year to come? Here, we are referring to tooling that automates, manages, and scales the entire application lifecycle, often leveraging remote, virtualized resources.",MC,NaN,NaN
84,QID36,Platform,"Which <b>cloud platforms, containerization/orchestration tools, package managers, build tools, and infrastructure as code solutions</b> have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the platform and want to continue to do so, please check both boxes in that row.)",Matrix,NaN,NaN
85,QID56,PlatformHaveEntry,"Was the cloud platforms, containerization/orchestration tools, package managers, build tools, and infrastructure as code solutions you use not listed above? List below, separated by a comma and a space for each, what <strong>you used in the past year</strong>.",TE,NaN,NaN
86,QID57,PlatformWantEntry,"Was the cloud platforms, containerization/orchestration tools, package managers, build tools, and infrastructure as code solutions you want to use not listed above? List below, separated by a comma and a space for each, what<strong>you want to use next year</strong>.",TE,NaN,NaN
87,QID47,WebframeChoice,"Did you work with web frameworks and web technologies in the last year or do you plan to in the year to come? Here, we are referring to technology that helps website and web apps materialize.",MC,NaN,NaN

### Завдання 1. Підрахунок загальної кількості респондентів

In [102]:
#  .nunique() - метод series, який підрахову кількість унікальних значень у стовпці ResponseID
unique_respondents = df['ResponseId'].nunique()
print( f'Загальна кількість респондентів: {unique_respondents}.')

Загальна кількість респондентів: 49191.

### Завдання 2. Аналіз повноти відповідей респондентів

In [101]:
# questions - створюємо множину назв питань, які присутні одночасно в qname та серед ствопців df.
# використання set() та qname.unique() створює множину унікальних qname,
names_in_df1 = set(df1['qname'].unique())
#  після чого ми беремо перетин із df.columns, щоб отримати лише ті питання, які реально існують в датафреймі.
all_columns = set(df.columns)
questions = names_in_df1 & all_columns
# dropna(): видалає тільки ті рядки де є промуски (NaN) у зазначиних стовпцях.
df_questions = df[list(questions)]
df_questions_nonull = df_questions.dropna()
# shape[0] повертає кільуість рядків - тобто кількість респондентів, які відповіли на всі ці питання.
q = df_questions_nonull.shape[0]
print(f'Кількість респондентів, які відповіли на всі ці питання: {q}.')

Кількість респондентів, які відповіли на всі ці питання: 0.

In [103]:
#перевіряємо результат
rows_with_nulls = df_questions.isnull().any(axis=1).sum()
print(f"Кількість респондентів всього: {df_questions.shape[0]}")
print(f"Кількість респондентів з пропусками: {rows_with_nulls}")
print(f'Кількість респондентів, які відповіли на всі ці питання: {q}.')

Кількість респондентів всього: 49191
Кількість респондентів з пропусками: 49191
Кількість респондентів, які відповіли на всі ці питання: 0.

### Завдання 3. Статистичний аналіз досвіду респондентів

In [82]:
df['WorkExp_filled'] = df['WorkExp'].fillna(0)
print(f'Міри центрацьної тенденції :')
print(f"Mean: {round(df['WorkExp_filled'].mean(),1)}")
print(f"Median: {round(df['WorkExp_filled'].median(),1)}")
print(f"Mode: {round(df['WorkExp_filled'].mode()[0],1)}")
# check the difference between mode and meen

Міри центрацьної тенденції :
Mean: 11.7
Median: 9.0
Mode: 0.0

### Завдання 4. Аналіз віддаленої роботи

In [104]:
#  Підраховуємо кількість рядків у df, де значення у відповідній колонці дорівнює "Remote". 
remote_workers = df['RemoteWork'].str.contains('Remote', case=False, na=False).sum() 
print(f'Кількість респондентів, які працюють віддалено: {remote_workers}.')

Кількість респондентів, які працюють віддалено: 17663.

### Завдання 5. Визначення популярності Python

In [105]:
# Створюємо новий стовпець worked_with_python, який містить Ture/False,
# де True означає, що респондент згадував Python у LanguageHaveWorkedWith.
# str.contains('...') - шукаємо слово 'python'
#  без урахування регісту та змінюємо пропуски (NaN) на False.
df['worked_with_python'] = df['LanguageHaveWorkedWith'].str.contains('Python', case=False, na=False)

In [148]:
# sum() - рахуємо загальну кількість респондентів, які працювали з Python.
# - обчислюємо частку таких респондентів у відсоткпх
worked_with_python = df['worked_with_python'].sum()
all_respondents = df['LanguageHaveWorkedWith'].count()
worked_with_python_percents = (worked_with_python / all_respondents) * 100
print(f'Відсоток респондентів які працювали з Python: {worked_with_python_percents: .2f}%')

Відсоток респондентів які працювали з Python:  58.31%

### Завдання 6. Аналіз шляхів навчання програмуванню

In [133]:
unique_learncode = df['LearnCode'].unique()
print(unique_learncode)

['Online Courses or Certification (includes all media types);Other online resources (e.g. standard search, forum, online community)'
 'Online Courses or Certification (includes all media types);Other online resources (e.g. standard search, forum, online community);Books / Physical media;Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange'
 'Online Courses or Certification (includes all media types);Videos (not associated with specific online course or certification);Technical documentation (is generated for/by the tool or system)'
 ...
 'Other online resources (e.g. standard search, forum, online community);Books / Physical media;Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);Colleague or on-the-job training;Blogs or podcasts;Coding Bootcamp;Games or coding challenges;School (i.e., University, College, etc)'
 'Online Courses or Certification (includes all media types);Other online resources (e.g. standard search, forum, online community);Books / Physical media;AI CodeGen tools or AI-enabled apps;Colleague or on-the-job training'
 'Online Courses or Certification (includes all media types);Stack Overflow or Stack Exchange;Blogs or podcasts;Games or coding challenges;School (i.e., University, College, etc)']

In [134]:
# Створюємо новий стовпець Learned_with_online_courses (True/False),
# де True означає, що респондент навчався через онлайн-курси (Використовуємо стовпчик LearnCode).
df['Learned_with_online_courses'] = df['LearnCode'].str.contains( 'Online Courses', case=False, na=False)

In [147]:
# Підраховуємо кількість респондентів, які обрали онлайн-курси.
learned_with_online_curses = df[df['Learned_with_online_courses'] == True].shape[0]
print(f'Кількість респондентів, які обрали онлайн-курси: {learned_with_online_curses}.')

Кількість респондентів, які обрали онлайн-курси: 10973.

### Завдання 7. Географічний аналіз компенсації Python-розробників

In [159]:
# df.worked_with_python — відбираємо лише тих, хто працював з Python.
# Видаляємо рядки, де відсутнє значення зарплати (ConvertedCompYearly).
# .groupby() — групуємо дані за країною (Country) і обчислюємо середню (mean) та медіанну (median) зарплату для кожної країни.
python_dev_compen = df.loc[(df['worked_with_python'] == True) & (df['ConvertedCompYearly'].notnull()),['Country', 'ConvertedCompYearly']]
py_progers_by_country = python_dev_compen.groupby('Country')['ConvertedCompYearly'].agg(['mean', 'median'])
py_progers_by_country_sort = py_progers_by_country.sort_values(by='median', ascending=False)

In [160]:
# py_progers_by_country_sort — таблиця з результатами.
py_progers_by_country_sort

                                   mean    median
Country
Oman                      390135.000000  390135.0
Andorra                   226103.500000  226103.5
United States of America  173298.590211  150000.0
Israel                    135828.365385  142594.0
Switzerland               156456.600000  142592.0
...                                 ...       ...
Cambodia                    1270.000000    1270.0
Afghanistan                22328.666667    1000.0
Togo                         354.000000     354.0
Palestine                     78.000000      78.0
Antigua and Barbuda            1.000000       1.0

[153 rows x 2 columns]

### Завдання 8. Аналіз освіти найбільш оплачуваних спеціалістів

In [166]:
# Вибираємо три стовпці: ResponseId, EdLevel, ConvertedCompYearly.
# Сортуємо за колонкою ConvertedCompYearly у порядку спадання (від більшої зарплати до меншої).
short_df = df[['ResponseId', 'EdLevel', 'ConvertedCompYearly']].sort_values(by='ConvertedCompYearly', ascending=False)

# reset_index(drop=True) — оновлюємо індекси після сортування, старий індекс видаляємо.
best_comp_df = short_df.reset_index(drop=True)

# head(5) — відбираємо перші 5 рядків (топ-5 респондентів з найвищою зарплатою).
best_comp_df.head(5)

,ResponseId,EdLevel,ConvertedCompYearly
0,34268,"Associate degree (A.A., A.S., etc.)",50000000.0
1,28701,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",33552715.0
2,43144,"Associate degree (A.A., A.S., etc.)",18387548.0
3,35354,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",15430267.0
4,45972,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",13921760.0

### Завдання 9 Аналіз популярності Python по віковим категоріям

In [189]:
# Рахуємо середнє значення колонки 'worked_with_python' для кожної вікової групи
# Це дає частку, яку ми множимо на 100 для отримання відсотків
python_by_age = df.groupby('Age')['worked_with_python'].mean() * 100

print('Популярність Python по віковим категоріям:')
print(python_by_age.round(2))

Популярність Python по віковим категоріям:
Age
18-24 years old      40.00
25-34 years old      36.94
35-44 years old      36.72
45-54 years old      38.63
55-64 years old      37.24
65 years or older    31.63
Prefer not to say    31.22
Name: worked_with_python, dtype: float64

### Завдання 10 Аналіз індустрій серед високооплачуваних віддалених працівників

In [195]:
# Знаходимо респондентів, які знаходяться в 75 перцентилі 
df_comp75 = df['ConvertedCompYearly'].quantile(0.75)
df_high_comp75 = df[df['ConvertedCompYearly'] >= df_comp75]

# відбираємо тільки тих, хто працює віддалено
mask = df_high_comp75['RemoteWork'].str.contains('Remote', case=False, na=False)
p75_on_remote = df_high_comp75[mask]

# визначаємо найрозповсюдженніші індустрії
industru_count = p75_on_remote.groupby('Industry')['Industry'].count()
top_indust_on_remote = industru_count.sort_values(ascending=False)
top_indust_on_remote

Industry
Software Development                          1503
Other:                                         267
Fintech                                        255
Healthcare                                     236
Internet, Telecomm or Information Services     192
Banking/Financial Services                     156
Government                                     118
Media & Advertising Services                    97
Retail and Consumer Services                    95
Computer Systems Design and Services            92
Transportation, or Supply Chain                 88
Manufacturing                                   81
Energy                                          71
Insurance                                       64
Higher Education                                48
Name: Industry, dtype: int64